---
# Usage: ansible-playbook -i PRIVATE-IP, playbooks/configure-ff.yml

- hosts: all

  tasks:
  - name: Install necessary packages
    yum:
      name: "{{ packages }}"
    vars:
      packages:
      - git
      - python3
    become: yes
    become_method: sudo

  - name: Pull down git repository
    git:
      repo: 'https://github.com/dmrickert/ff_bot.git'
      dest: ~/ff_bot/
      version: personal-tweaks 
      force: yes

  - name: Install pip requirements
    pip:
      requirements: ~/ff_bot/requirements.txt
      executable: pip3
      extra_args: '--user'
    ignore_errors: True

  - name: Copy Configuration file to the git repo
    copy:
      src: ff-bot-config
      dest: ~/ff_bot/ff-bot-config

  - name: Kill process if it exists
    shell: pkill -f 'python3 ~/ff_bot/ff_bot/ff_bot.py' | cat
    ignore_errors: True

  # Really should turn this into a service at some point
  - name: Start our app
    shell: "source ~/ff_bot/ff-bot-config && nohup python3 ~/ff_bot/ff_bot/ff_bot.py </dev/null >/dev/null 2>&1 &"

  - name: Verify our app is running
    shell: pgrep -f 'python3 /home/ec2-user/ff_bot/ff_bot/ff_bot.py'
